spring:
  mvc:
    mapping: "/**"
    allowed:
      credentials: true
      origin-patterns: "*"
      headers: "*"
      methods: "*"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  cloud:
    aws:
      region: us-east-1
      credentials:
        access-key: access
        secret-key: secret
      bucket:
        default:
          name: tt-nts
server:
  servlet:
    context-path: /api/v1/
  port: 8888
logging:
  level:
    org:
      springframework:
        web: DEBUG
